version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: cartshopshoes
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shopshoes-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456789"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eureka Discovery Server
  discovery-server:
    build:
      context: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - shopshoes-network
    restart: on-failure

  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopshoes-network
    depends_on:
      - discovery-server
    restart: on-failure

  # Authentication Service
  auth-service:
    build:
      context: ./authentication-service
    container_name: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopshoes-network
    depends_on:
      - mysql
      - discovery-server
    restart: on-failure

  # Product Service
  product-service:
    build:
      context: ./product-service
    container_name: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopshoes-network
    depends_on:
      - mysql
      - discovery-server
    restart: on-failure

  # Cart Service
  cart-service:
    build:
      context: ./cart-service
    container_name: cart-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopshoes-network
    depends_on:
      - mysql
      - discovery-server
      - product-service
    restart: on-failure

  # Invoice Service
  invoice-service:
    build:
      context: ./invoice-service
    container_name: invoice-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopshoes-network
    depends_on:
      - mysql
      - discovery-server
    restart: on-failure

networks:
  shopshoes-network:

volumes:
  mysql-data: 