-- Tạo database
CREATE DATABASE IF NOT EXISTS SHOPSHOESINVOICE;
USE SHOPSHOESINVOICE;

-- Tạo bảng INVOICE
CREATE TABLE IF NOT EXISTS INVOICE (
    INVOICE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SHIP_ADDRESS VARCHAR(255),
    STATUS VARCHAR(255),
    TOTAL_PRICE DECIMAL(19,2),
    USER_ID BIGINT NOT NULL
);

-- Tạo bảng INVOICE_DETAILS
CREATE TABLE IF NOT EXISTS INVOICE_DETAILS (
    INVOICE_DETAILS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DISCOUNT DECIMAL(19,2),
    PRICE DECIMAL(19,2),
    QUANTITY INT NOT NULL,
    INVOICE_ID BIGINT,
    PRODUCT_ID BIGINT,
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(INVOICE_ID)
);

-- Tạo bảng PRODUCTS (cần thiết cho khóa ngoại)
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_PRICE DECIMAL(19,2),
    QUANTITY INT NOT NULL
);

-- Thêm khóa ngoại cho PRODUCT_ID
ALTER TABLE INVOICE_DETAILS 
ADD CONSTRAINT FK_INVOICE_DETAILS_PRODUCT 
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID);

-- Chèn dữ liệu mẫu vào bảng PRODUCTS
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_PRICE, QUANTITY) VALUES
('Nike Air Force 1', 2000000, 50),
('Adidas Ultraboost', 3000000, 30),
('Converse Chuck Taylor', 1500000, 40);

-- Trigger cập nhật số lượng sản phẩm khi có thay đổi trong chi tiết hóa đơn
DELIMITER //
CREATE TRIGGER TRG_UPDATE_PRODUCT_QUANTITY
AFTER INSERT ON INVOICE_DETAILS
FOR EACH ROW
BEGIN
    UPDATE PRODUCTS
    SET QUANTITY = QUANTITY - NEW.QUANTITY
    WHERE PRODUCT_ID = NEW.PRODUCT_ID;
END;
//
DELIMITER ;

-- Trigger kiểm tra số lượng sản phẩm trong kho khi tạo hóa đơn
DELIMITER //
CREATE TRIGGER CHECK_PRODUCT_QUANTITY
BEFORE INSERT ON INVOICE_DETAILS
FOR EACH ROW
BEGIN
    DECLARE V_AVAILABLE_QUANTITY INT;
    SELECT QUANTITY INTO V_AVAILABLE_QUANTITY
    FROM PRODUCTS
    WHERE PRODUCT_ID = NEW.PRODUCT_ID;

    IF NEW.QUANTITY > V_AVAILABLE_QUANTITY THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Số lượng sản phẩm không đủ trong kho';
    END IF;
END;
//
DELIMITER ;

-- Trigger tính tiền hóa đơn
DELIMITER //
CREATE TRIGGER TRG_INVOICE_VALUE
AFTER INSERT ON INVOICE_DETAILS
FOR EACH ROW
BEGIN
    DECLARE INVOICE_VALUE DECIMAL(19,2);
    SELECT SUM(QUANTITY * PRICE) INTO INVOICE_VALUE
    FROM INVOICE_DETAILS
    WHERE INVOICE_ID = NEW.INVOICE_ID;

    UPDATE INVOICE
    SET TOTAL_PRICE = INVOICE_VALUE
    WHERE INVOICE_ID = NEW.INVOICE_ID;
END;
//
DELIMITER ; 